global.settings = {
    OWNER_NUMBERS: "2349131352674", // replace with your number
    OWNER_NAME: '𝗘𝗞𝗦𝗨 𝗛𝗼𝗺𝗲𝘀 & 𝗣𝗿𝗼𝗽𝗲𝗿𝘁𝗶𝗲𝘀', // desired name
    BOT_NAME: "𝗘𝗞𝗦𝗨 𝗛𝗼𝗺𝗲𝘀 & 𝗣𝗿𝗼𝗽𝗲𝗿𝘁𝗶𝗲𝘀", // desired name
    VERSION: 'V1.0.0',
    SESSION_ID: 'eyJub2lzZUtleSI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoicVBvVjE1bGVveEZKcGYwR2dzbDBGZXFYeHhUaThya0duNGFpdWZhK0lIbz0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiSzRRN0RnQWRaWWI5VmZJT3RkSCsvZkNWbUtFcXBXd0Z6VlpyWmJ4TDRqYz0ifX0sInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyIjp7InByaXZhdGUiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJXQkhtYmNKRy9kNUdCSU9nUkhjM0JZRjJ4Q0YwR2FESDFRSEhualY0K0dNPSJ9LCJwdWJsaWMiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJ3SG9hMzVkK01lcHh5akE0TDRESUpTakM0UmRGUTc3aTRMYjBtRHNjLzJJPSJ9fSwic2lnbmVkSWRlbnRpdHlLZXkiOnsicHJpdmF0ZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IjJHMnFEUG5xMDNZNWQ1eVBLRVFsUnJ0M0V4VE8zbzNKK0UwSFN5M29HRUE9In0sInB1YmxpYyI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IlR4QTc1NmpDVnplSnZ4VFBpVThhdERTTTF3NFBlbjh0VDNwSnN2M1Rhbms9In19LCJzaWduZWRQcmVLZXkiOnsia2V5UGFpciI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiRU9FWlBaV3drWEovNDdMdFV3WklEMFlpTURNOFpIZFVxa1c2Vys1OVVIZz0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoid0lBdm5ldkk2SE81THNhMDJGcFdLSXU1ODhhUmVYNmhhdTNyWVNERzZEMD0ifX0sInNpZ25hdHVyZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IlJTMlRUR0tTanprODhLMy9aeWc1UjVZREhtWk01TUVnc2Y5QkNlejY0ZkZqcGtQNmJsOTJkWE8vek1pUHRJNlpra1VpUkQrQ2pIWjVRTHJiZFFjb0NRPT0ifSwia2V5SWQiOjF9LCJyZWdpc3RyYXRpb25JZCI6MjIzLCJhZHZTZWNyZXRLZXkiOiJzYzhVUUhlNEpoOTQ3eVdqYmxKR1BjNWxrelVpb3NsQ0FOY3lQU2JjSXhzPSIsInByb2Nlc3NlZEhpc3RvcnlNZXNzYWdlcyI6W10sIm5leHRQcmVLZXlJZCI6MzEsImZpcnN0VW51cGxvYWRlZFByZUtleUlkIjozMSwiYWNjb3VudFN5bmNDb3VudGVyIjowLCJhY2NvdW50U2V0dGluZ3MiOnsidW5hcmNoaXZlQ2hhdHMiOmZhbHNlfSwiZGV2aWNlSWQiOiJRM0lUOWlyU1J2V3BfejhRNTJvSnJ3IiwicGhvbmVJZCI6IjU2MWEwMjZlLWNjMjUtNDZhNS1hMDMyLTU2OTk2NjQxMjMwNSIsImlkZW50aXR5SWQiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJjNEpNQzJYa0ZuUHdtRFMzbDZ0WmREWDAzMW89In0sInJlZ2lzdGVyZWQiOnRydWUsImJhY2t1cFRva2VuIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiRWNKSTZVTWN3YlFDckZyalk0SVMrazBXcDRBPSJ9LCJyZWdpc3RyYXRpb24iOnt9LCJwYWlyaW5nQ29kZSI6IjYxNkJDQjlIIiwibWUiOnsiaWQiOiIyMzQ5MTMxMzUyNjc0OjIxQHMud2hhdHNhcHAubmV0IiwibmFtZSI6IkVLU1UgSG9tZXMgJiBQcm9wZXJ0aWVzIn0sImFjY291bnQiOnsiZGV0YWlscyI6IkNQaXFtOEFERUtlamxia0dHQUlnQUNnQSIsImFjY291bnRTaWduYXR1cmVLZXkiOiJFaDFzVHBEYzBXNjg2Mm1QVlh1ZXdBdlBCVEFsbDdiM2F4WTM1OXVNRWk4PSIsImFjY291bnRTaWduYXR1cmUiOiJHbW95dXdmLy9oeCtuWEUxb1prK0x0cTVSQkxkMy94THp4ZVVUVk5wMXdJRzRSYmxOU2dkYlJUczJVSmtxazBKYU1QWDJxN2V5N0RNVWFNV2VFZmFBdz09IiwiZGV2aWNlU2lnbmF0dXJlIjoiWk1pKzRlajQwbW0zdG5WanJQQlVvTjlCam81bmc3RklBZ0s5RHpsRzFITkhzbXkvWnQ4U3ZkUXZ5YVpUaC93YVlja01uVy9lNWFBUXhNOUtyVXNmQUE9PSJ9LCJzaWduYWxJZGVudGl0aWVzIjpbeyJpZGVudGlmaWVyIjp7Im5hbWUiOiIyMzQ5MTMxMzUyNjc0OjIxQHMud2hhdHNhcHAubmV0IiwiZGV2aWNlSWQiOjB9LCJpZGVudGlmaWVyS2V5Ijp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiQlJJZGJFNlEzTkZ1dk90cGoxVjduc0FMendVd0paZTI5MnNXTitmYmpCSXYifX1dLCJwbGF0Zm9ybSI6InNtYmEiLCJsYXN0QWNjb3VudFN5bmNUaW1lc3RhbXAiOjE3MzA0OTg5OTZ9', //put your session id between ''
    MONGO_DB_URL: 'mongodb+srv://miracle32669:Iyanu1234@cluster0.m7glm.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0',
    WORK_MODE: "Public",
    TIME_ZONE: "Africa/Lagos",
    ANTI_VIEWONCE: true,
    AUTO_READ_STATUS: true,
    ALWAYS_ONLINE: true,
    READ_ALL_MESSAGES: false,
    PREFIX: [".", "/", "!"],
    WELCOME_MESSAGE: "Hello! I'm KORD-AI, your friendly WhatsApp bot.",
    DEFAULT_TRANSLATION_LANG: "en",
    COMMAND_COOLDOWN_TIME_IN_MS: 2000,
    MAX_COMMANDS_PER_MINUTE: 10,
    MAX_DOWNLOAD_SIZE: 100,
    API_KEYS: {
        OPENWEATHERMAP_API_KEY: ''
    },
    isHackEnable:true,
    SAFE_SEARCH: true,
    REJECT_CALLS: true,
    SEND_WELCOME_MESSAGE: false,
    WELCOME_MESSAGE: "👋 Welcome to the group! We're glad to have you here. 😊",
    DELETE_WA_LINKS: false,
    BAD_WORD_FILTER: true,
    BAD_WORDS: ['badword1', 'badword2', 'fuck', 'bitch', 'hentai'],
    ANTI_DELETE_ENABLED: true // Add this line for anti-delete feature
};
